In [1]:
import numpy as np

from resin_spectral_analysis.spectrummodels import ha_model, a_b_model, a_b_c_model, fit_ha_model, fit_a_b_model, fit_a_b_c_model

## ha_model

In [2]:
ha = 10.0
temp_z = np.linspace(0, 20, 3)
ha_model(temp_z, ha)

array([1.        , 0.36787944, 0.13533528])

In [3]:
params, cov = fit_ha_model(temp_z, ha_model(temp_z, ha))
print(params)
print(cov)
assert np.allclose(params, [ha])
assert np.allclose(cov, [0])

[10.]
[[8.79707655e-21]]


## a_b_model

In [4]:
a = 0.5
b = 10.0
temp_z = np.linspace(0, 20, 3)
a_b_model(temp_z, a, b)

array([1.        , 0.68393972, 0.56766764])

In [5]:
params, cov = fit_a_b_model(temp_z, a_b_model(temp_z, a, b))
print(params)
print(cov)
assert np.allclose(params, [a, b])
assert np.allclose(cov, [[0, 0], [0, 0]])

[0.5        9.99999994]
[[2.27356733e-18 1.01708522e-16]
 [1.01708522e-16 5.00155767e-15]]


## a_b_c_model

In [6]:
a = 0.5
b = 10.0
c = 0.3
temp_z = np.linspace(0, 20, 7)
a_b_c_model(temp_z, a, b, c)

array([0.8       , 0.65826566, 0.55670856, 0.48393972, 0.43179857,
       0.3944378 , 0.36766764])

In [7]:
params, cov = fit_a_b_c_model(temp_z, a_b_c_model(temp_z, a, b, c))
print(params)
print(cov)
assert np.allclose(params, [a, b, c])
assert np.allclose(cov, [[0, 0, 0], [0, 0, 0], [0, 0, 0]])

[0.5       9.9999999 0.3      ]
[[ 1.69242849e-18  6.51574336e-17 -1.64793859e-18]
 [ 6.51574336e-17  4.07694940e-15 -8.45727674e-17]
 [-1.64793859e-18 -8.45727674e-17  1.94374565e-18]]
