In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
# %matplotlib widget

from resin_spectral_analysis.utilities import ArrayParams, find_index_of_nearest, find_index_of_max, shift, shift_peak_wavelength


# shift

In [2]:
start_array = np.array([x + 1 for x in range(10)])

start_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
shift_left_4 = shift(start_array, -4)
shift_left_4

array([ 5,  6,  7,  8,  9, 10,  0,  0,  0,  0])

In [5]:
shift_right_4_fill_with_20 = shift(start_array, 4, fill_value=20)
shift_right_4_fill_with_20

array([20, 20, 20, 20,  1,  2,  3,  4,  5,  6])

# shift_peak_wavelength

In [6]:
w = np.linspace(360, 400, 9)
w

array([360., 365., 370., 375., 380., 385., 390., 395., 400.])

In [7]:
p = np.array([1, 2, 3, 4, 3.5, 2.5, 1.5, 1.0, 1.0])
p

array([1. , 2. , 3. , 4. , 3.5, 2.5, 1.5, 1. , 1. ])

In [8]:
shift_peak_wavelength(385, w, p)

array([0. , 0. , 1. , 2. , 3. , 4. , 3.5, 2.5, 1.5])