In [2]:
import typing

import numpy as np
import matplotlib.pyplot as plt
%matplotlib widget

from scipy.optimize import curve_fit
import scipy.integrate as integrate

import spectra.data as data
from spectra.resin import ResinConstituentAbsorber, ResinConstituentMonomer, Resin

# ArrayParams class

In [5]:
class ArrayParams(typing.NamedTuple):
    min_value: float
    max_value: float
    num_pnts: int
        
temp = ArrayParams(300, 440, 11)
temp

ArrayParams(min_value=300, max_value=440, num_pnts=11)

In [6]:
print(*temp)

300 440 11


In [7]:
np.linspace(*temp)

array([300., 314., 328., 342., 356., 370., 384., 398., 412., 426., 440.])

# Irradiance class

In [16]:
class Irradiance:
    
    def __init__(self, source, resin, array_params):
        self.source = source
        self.resin = resin
        self.array_params = array_params
        
        self.wavelengths = np.linspace(*self.array_params)
        
        self.source_spectrum = self.source.calc_power(self.wavelengths)
        self.absorption_coeff_inv_um = self.resin.calc_absorption_coef_inv_um(self.wavelengths)
        
    def __call__(self, z_um):
        print("----CALLED----")
        

In [17]:
# Create resin
pegda = ResinConstituentMonomer(data.monomers['PEGDA'], 100)
avobenzone = ResinConstituentAbsorber(
    data.absorbers['avobenzone_in_PEGDA_2017-04-13'],
    0.38
)
irgacure819 = ResinConstituentAbsorber(
    data.photoinitiators['irgacure819_in_PEGDA_2017-04-13'],
    1.0
)
resin = Resin(monomers=pegda, absorbers=avobenzone, photoinitiators=irgacure819)
print(resin.name)

# Source
source = data.sources['HR3.2_365nm_370nm_short_pass_filter-2019-12-31']

# Wavelength array parameters
wavelength_array_parameters = ArrayParams(300, 440, 201)

i_temp = Irradiance(source=source, resin=resin, array_params=wavelength_array_parameters)

PEG-100__Avo-0.38__Irg-1


In [18]:
vars(i_temp)

{'source': <spectra.sourcespectrum.SourceSpectrum at 0x7fc7ba4a8790>,
 'resin': <spectra.resin.Resin at 0x7fc7ba5210d0>,
 'array_params': ArrayParams(min_value=300, max_value=440, num_pnts=201),
 'wavelengths': array([300. , 300.7, 301.4, 302.1, 302.8, 303.5, 304.2, 304.9, 305.6,
        306.3, 307. , 307.7, 308.4, 309.1, 309.8, 310.5, 311.2, 311.9,
        312.6, 313.3, 314. , 314.7, 315.4, 316.1, 316.8, 317.5, 318.2,
        318.9, 319.6, 320.3, 321. , 321.7, 322.4, 323.1, 323.8, 324.5,
        325.2, 325.9, 326.6, 327.3, 328. , 328.7, 329.4, 330.1, 330.8,
        331.5, 332.2, 332.9, 333.6, 334.3, 335. , 335.7, 336.4, 337.1,
        337.8, 338.5, 339.2, 339.9, 340.6, 341.3, 342. , 342.7, 343.4,
        344.1, 344.8, 345.5, 346.2, 346.9, 347.6, 348.3, 349. , 349.7,
        350.4, 351.1, 351.8, 352.5, 353.2, 353.9, 354.6, 355.3, 356. ,
        356.7, 357.4, 358.1, 358.8, 359.5, 360.2, 360.9, 361.6, 362.3,
        363. , 363.7, 364.4, 365.1, 365.8, 366.5, 367.2, 367.9, 368.6,
        3

In [19]:
i_temp()

TypeError: __call__() missing 1 required positional argument: 'z_um'

# OLD

In [33]:
# See https://medium.com/@beef_and_rice/mastering-pythons-getitem-and-slicing-c94f85415e1c
class LinSpace:
    
    def __init__(self, vmin, vmax, num_pnts):
        self.min = vmin
        self.max = vmax
        self.num_pnts = num_pnts
        self.data = np.linspace(self.min, self.max, self.num_pnts)
        
    def __getitem__(self, key):
        return self.data[key]
    
    def __repr__(self):
        return str(self.data)

    def __len__(self):
        return len(self.data)

    def __max__(self):
        return np.max(self.data)

    def __min__(self):
        return np.min(self.data)


In [34]:
wavelengths = LinSpace(300, 440, 201)
vars(wavelengths)

{'min': 300,
 'max': 440,
 'num_pnts': 201,
 'data': array([300. , 300.7, 301.4, 302.1, 302.8, 303.5, 304.2, 304.9, 305.6,
        306.3, 307. , 307.7, 308.4, 309.1, 309.8, 310.5, 311.2, 311.9,
        312.6, 313.3, 314. , 314.7, 315.4, 316.1, 316.8, 317.5, 318.2,
        318.9, 319.6, 320.3, 321. , 321.7, 322.4, 323.1, 323.8, 324.5,
        325.2, 325.9, 326.6, 327.3, 328. , 328.7, 329.4, 330.1, 330.8,
        331.5, 332.2, 332.9, 333.6, 334.3, 335. , 335.7, 336.4, 337.1,
        337.8, 338.5, 339.2, 339.9, 340.6, 341.3, 342. , 342.7, 343.4,
        344.1, 344.8, 345.5, 346.2, 346.9, 347.6, 348.3, 349. , 349.7,
        350.4, 351.1, 351.8, 352.5, 353.2, 353.9, 354.6, 355.3, 356. ,
        356.7, 357.4, 358.1, 358.8, 359.5, 360.2, 360.9, 361.6, 362.3,
        363. , 363.7, 364.4, 365.1, 365.8, 366.5, 367.2, 367.9, 368.6,
        369.3, 370. , 370.7, 371.4, 372.1, 372.8, 373.5, 374.2, 374.9,
        375.6, 376.3, 377. , 377.7, 378.4, 379.1, 379.8, 380.5, 381.2,
        381.9, 382.6, 383

In [35]:
wavelengths

[300.  300.7 301.4 302.1 302.8 303.5 304.2 304.9 305.6 306.3 307.  307.7
 308.4 309.1 309.8 310.5 311.2 311.9 312.6 313.3 314.  314.7 315.4 316.1
 316.8 317.5 318.2 318.9 319.6 320.3 321.  321.7 322.4 323.1 323.8 324.5
 325.2 325.9 326.6 327.3 328.  328.7 329.4 330.1 330.8 331.5 332.2 332.9
 333.6 334.3 335.  335.7 336.4 337.1 337.8 338.5 339.2 339.9 340.6 341.3
 342.  342.7 343.4 344.1 344.8 345.5 346.2 346.9 347.6 348.3 349.  349.7
 350.4 351.1 351.8 352.5 353.2 353.9 354.6 355.3 356.  356.7 357.4 358.1
 358.8 359.5 360.2 360.9 361.6 362.3 363.  363.7 364.4 365.1 365.8 366.5
 367.2 367.9 368.6 369.3 370.  370.7 371.4 372.1 372.8 373.5 374.2 374.9
 375.6 376.3 377.  377.7 378.4 379.1 379.8 380.5 381.2 381.9 382.6 383.3
 384.  384.7 385.4 386.1 386.8 387.5 388.2 388.9 389.6 390.3 391.  391.7
 392.4 393.1 393.8 394.5 395.2 395.9 396.6 397.3 398.  398.7 399.4 400.1
 400.8 401.5 402.2 402.9 403.6 404.3 405.  405.7 406.4 407.1 407.8 408.5
 409.2 409.9 410.6 411.3 412.  412.7 413.4 414.1 41

In [36]:
len(wavelengths)

201

In [37]:
max(wavelengths)

440.0

In [32]:
np.max(wavelengths)

TypeError: 'int' object is not callable

In [38]:
min(wavelengths)

300.0

In [10]:
wavelengths[0:5]

array([300. , 300.7, 301.4, 302.1, 302.8])

In [11]:
wavelengths[0:10:2]

array([300. , 301.4, 302.8, 304.2, 305.6])

In [12]:
wavelengths[(0,5,8)]

IndexError: too many indices for array

In [13]:
wavelengths[1]

300.7

In [14]:
wavelengths[0,1,2]

IndexError: too many indices for array

In [15]:
temp = [a for a in range(11)]
temp

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
temp[0]

0

In [18]:
temp[(0,4)]

TypeError: list indices must be integers or slices, not tuple